# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }

# and alacritty.toml should import that file under [general]

[colors.primary]
background = "#191817"
foreground = "#EFEEE9"

[colors.normal]
black   = "#403F3E"
red     = "#1B1510"
green   = "#4A3D27"
yellow  = "#625033"
blue    = "#8C7A40"
magenta = "#6C8BAA"
cyan    = "#9C9B90"
white   = "#DFDED7"

[colors.bright]
black   = "#9C9B97"
red     = "#231C15"
green   = "#635134"
yellow  = "#836B44"
blue    = "#BBA355"
magenta = "#90B9E3"
cyan    = "#D0CEC0"
white   = "#DFDED7"
