# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }

# and alacritty.toml should import that file under [general]

[colors.primary]
background = "#171616"
foreground = "#D9DADB"

[colors.normal]
black   = "#3E3D3D"
red     = "#313031"
green   = "#404041"
yellow  = "#504F51"
blue    = "#5F5F62"
magenta = "#6E6F72"
cyan    = "#6E6F72"
white   = "#C1C1C3"

[colors.bright]
black   = "#878788"
red     = "#414041"
green   = "#555557"
yellow  = "#6A6A6D"
blue    = "#7E7F82"
magenta = "#939498"
cyan    = "#939498"
white   = "#C1C1C3"
