# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(191817)
$foreground = rgb(EFEEE9)
$color0 = rgb(403F3E)
$color1 = rgb(1B1510)
$color2 = rgb(4A3D27)
$color3 = rgb(625033)
$color4 = rgb(8C7A40)
$color5 = rgb(6C8BAA)
$color6 = rgb(9C9B90)
$color7 = rgb(DFDED7)
$color8 = rgb(9C9B97)
$color9 = rgb(231C15)
$color10 = rgb(635134)
$color11 = rgb(836B44)
$color12 = rgb(BBA355)
$color13 = rgb(90B9E3)
$color14 = rgb(D0CEC0)
$color15 = rgb(DFDED7)
