# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1F22)
$foreground = rgb(E2F1F0)
$color0 = rgb(454548)
$color1 = rgb(1C1D29)
$color2 = rgb(424D60)
$color3 = rgb(55596B)
$color4 = rgb(62768F)
$color5 = rgb(6D839F)
$color6 = rgb(80A19F)
$color7 = rgb(CDE2E1)
$color8 = rgb(8F9F9E)
$color9 = rgb(252736)
$color10 = rgb(576780)
$color11 = rgb(71778F)
$color12 = rgb(839DBF)
$color13 = rgb(91AFD4)
$color14 = rgb(ABD7D4)
$color15 = rgb(CDE2E1)
