# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171616)
$foreground = rgb(D9DADB)
$color0 = rgb(3E3D3D)
$color1 = rgb(313031)
$color2 = rgb(404041)
$color3 = rgb(504F51)
$color4 = rgb(5F5F62)
$color5 = rgb(6E6F72)
$color6 = rgb(6E6F72)
$color7 = rgb(C1C1C3)
$color8 = rgb(878788)
$color9 = rgb(414041)
$color10 = rgb(555557)
$color11 = rgb(6A6A6D)
$color12 = rgb(7E7F82)
$color13 = rgb(939498)
$color14 = rgb(939498)
$color15 = rgb(C1C1C3)
