#Monitor HDMI (Esquerda)
# Ele começa no pixel 0
monitor=HDMI-A-2,1366x768@60,0x0,1.0

# Monitor do Notebook (Direita - Principal)
# Ele começa no pixel 1366 (logo após o HDMI terminar)
monitor=eDP-1,1920x1080@60,1366x0,1
