
[window]
# Preenchimento interno (padding)
padding.x = 12
padding.y = 12

dimensions.columns = 130
dimensions.lines = 30

decorations = "none"
# O título da janela muda conforme o comando em execução.
dynamic_title = false

[font]
normal.family = "JetBrains Mono"
normal.style = "Regular"
size = 14.0

offset.y = 1

[cursor]
style = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key = "Equals",   mods = "Alt", action = "IncreaseFontSize" },
    { key = "Plus",     mods = "Alt", action = "IncreaseFontSize" },
    { key = "Minus",    mods = "Alt", action = "DecreaseFontSize" },
    { key = "Key0",     mods = "Control", action = "ResetFontSize" },
    { key = "C",        mods = "Control|Shift", action = "Copy" },
    { key = "V",        mods = "Control|Shift", action = "Paste" }
]

[general]
import = ["~/.config/alacritty/colors.toml"]
